name: Continuous Integration

on: [push, pull_request]

jobs:
  build-and-deploy:

    runs-on: macos-latest 

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
